package com.demo.common.model;

import com.demo.common.model.base.BaseAppraisedRates;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AppraisedRates extends BaseAppraisedRates<AppraisedRates> {
	public static final AppraisedRates dao = new AppraisedRates().dao();
}
