package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAppraisedRates<M extends BaseAppraisedRates<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCreatedAt(java.util.Date createdAt) {
		set("createdAt", createdAt);
		return (M)this;
	}
	
	public java.util.Date getCreatedAt() {
		return get("createdAt");
	}

	public M setUserAddId(java.lang.String userAddId) {
		set("userAddId", userAddId);
		return (M)this;
	}
	
	public java.lang.String getUserAddId() {
		return getStr("userAddId");
	}

	public M setUpdatedAt(java.util.Date updatedAt) {
		set("updatedAt", updatedAt);
		return (M)this;
	}
	
	public java.util.Date getUpdatedAt() {
		return get("updatedAt");
	}

	public M setUserModifyId(java.lang.String userModifyId) {
		set("userModifyId", userModifyId);
		return (M)this;
	}
	
	public java.lang.String getUserModifyId() {
		return getStr("userModifyId");
	}

	public M setBuyRate(java.lang.Double buyRate) {
		set("buy_rate", buyRate);
		return (M)this;
	}
	
	public java.lang.Double getBuyRate() {
		return getDouble("buy_rate");
	}

	public M setSellRate(java.lang.Double sellRate) {
		set("sell_rate", sellRate);
		return (M)this;
	}
	
	public java.lang.Double getSellRate() {
		return getDouble("sell_rate");
	}

	public M setMaxRate(java.lang.Double maxRate) {
		set("max_rate", maxRate);
		return (M)this;
	}
	
	public java.lang.Double getMaxRate() {
		return getDouble("max_rate");
	}

	public M setMinRate(java.lang.Double minRate) {
		set("min_rate", minRate);
		return (M)this;
	}
	
	public java.lang.Double getMinRate() {
		return getDouble("min_rate");
	}

	public M setRate24hAgo(java.lang.Double rate24hAgo) {
		set("rate_24h_ago", rate24hAgo);
		return (M)this;
	}
	
	public java.lang.Double getRate24hAgo() {
		return getDouble("rate_24h_ago");
	}

}
